#Query 2
SELECT U.USER_ID, COUNT(*) AS NUMFRIENDS
FROM FRIENDS F, USERS U
WHERE F.USER1_ID = U.USER_ID OR F.USER2_ID = U.USER_ID
GROUP BY U.USER_ID
HAVING COUNT(*) > 80
ORDER BY NUMFRIENDS DESC;


#Query 4
SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME
FROM (
  SELECT P.PHOTO_ID, COUNT(*) AS NUMTAGS, T.TAG_SUBJECT_ID AS TAG_ID
  FROM PHOTOS P, TAGS T
  WHERE P.PHOTO_ID = T.TAG_PHOTO_ID AND ROWNUM <= 10
  GROUP BY P.PHOTO_ID
  HAVING COUNT(*) > 0
  ORDER BY NUMTAGS DESC, P.PHOTO_ID ASC) I, USERS U
WHERE U.USER_ID = I.TAG_ID
GROUP BY I.TAG_ID



#Query 6
SELECT U.USER_ID


#Query 8
SELECT
